name: CI
on: [push, pull_request]

jobs:
  lint-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: GitGuardian scan for secrets
      uses: GitGuardian/ggshield-action@v1
      env:
        GITGUARDIAN_API_KEY: ${{ secrets.GITGUARDIAN_API_KEY }}
    - uses: actions/setup-python@v5
      with:
        python-version: '3.10'
    - run: pip install -r requirements.txt -r requirements-dev.txt
    - run: isort --check-only .
    - run: black --check .
    - run: pytest -q 