# Workflow name displayed in the GitHub Actions UI.
name: Job Scraper CI/CD

# Define triggers for this workflow.
on:
  # Trigger on pushes to the 'main' branch for continuous integration (CI) and immediate deployment checks.
  push:
    branches:
      - main
  # Schedule recurring runs for automated job scraping.
  # '0 2 * * *' means 02:00 AM UTC daily. Adjust cron expression as needed.
  schedule:
    - cron: '0 2 * * *'
  # Allow manual triggering from the GitHub Actions UI.
  # Includes an input for enabling debug logging, useful for troubleshooting specific runs.
  workflow_dispatch:
    inputs:
      debug_enabled:
        description: 'Enable verbose debug logging for this run?'
        required: false
        type: boolean
        default: false

# Define the jobs to be executed in this workflow.
jobs:
  scrape_and_notify:
    # Specify the runner environment. ubuntu-latest is a standard choice for Linux-based containers.
    runs-on: ubuntu-latest
    # Define environment variables available to all steps in this job.
    env:
      # Map the workflow_dispatch input to an environment variable consumed by the Python script.
      DEBUG_ENABLED: ${{ github.event.inputs.debug_enabled }}

    steps:
      - name: Checkout repository code
        # Uses a standard action to clone the repository, making code available to subsequent steps.
        uses: actions/checkout@v4

      # --- NEW STEPS FOR CODE QUALITY CHECKS ---
      - name: Set up Python for formatting/linting checks
        uses: actions/setup-python@v5
        with:
          python-version: '3.11' # Specify your exact Python version, e.g., '3.9', '3.10', '3.11', '3.12'

      - name: Install Black for formatting check
        run: pip install black

      - name: Check code formatting with Black
        run: black . --check
        # This step will fail the workflow if the code is not formatted according to Black's rules.
        # This ensures consistent code style before building the Docker image.

      - name: Install Flake8 for linting check
        run: pip install flake8

      - name: Check code linting with Flake8
        run: flake8 .

      # Install Mypy for type checking
      - name: Install Mypy for type checking
        run: pip install mypy

      - name: Run Mypy static type checker
        run: mypy . --ignore-missing-imports
        # This step will fail the workflow if there are type checking errors in the code.
        
      # Install Pytest for running tests
      - name: Install Pytest
        run: pip install pytest

      # Install Selenium and Telegram dependencies for the tests
      - name: Install Selenium and Telegram dependencies
        run: pip install selenium python-telegram-bot

      - name: Run Pytest
        run: pytest

      - name: Cache Posted Jobs File
        # Caches the 'posted_jobs.txt' file across workflow runs. This is critical for
        # maintaining the history of sent jobs and preventing duplicate notifications.
        id: cache-posted-jobs
        uses: actions/cache@v4
        with:
          path: posted_jobs.txt # The file to cache on the runner's filesystem.
          key: ${{ runner.os }}-posted-jobs # Unique key for the cache, incorporating OS for specificity.
          restore-keys: |
            ${{ runner.os }}-posted-jobs # Ensures cache restoration even if the exact key doesn't match.

      - name: Set up Docker Buildx
        # Initializes Docker Buildx, enhancing Docker build capabilities (e.g., for multi-platform builds, caching).
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        # Authenticates with Docker Hub using securely stored GitHub Secrets.
        # This is required to push new Docker images to your repository.
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push Docker image to Docker Hub
        # Builds the Docker image from the Dockerfile and pushes it to Docker Hub.
        # Tags the image with 'latest' and the current Git commit SHA for version control.
        id: docker_build
        uses: docker/build-push-action@v5
        with:
          context: . # Specifies the build context as the current directory.
          push: true # Instructs the action to push the built image to Docker Hub.
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME && format('{0}/devops-job-scraper:latest', secrets.DOCKERHUB_USERNAME) }}
            ${{ secrets.DOCKERHUB_USERNAME && format('{0}/devops-job-scraper:{1}', secrets.DOCKERHUB_USERNAME, github.sha) }}
          # Leverages GitHub Actions cache for Docker layer caching, significantly speeding up subsequent builds.
          cache-from: type=gha,scope=build
          cache-to: type=gha,scope=build,mode=max

      - name: Run Docker container for job scraping
        # Executes the newly built (and pushed) Docker image.
        # Environment variables and the persisted 'posted_jobs.txt' are mounted/passed.
        run: |
          # Define internal container path for the posted jobs file.
          CONTAINER_POSTED_JOBS_PATH="/app/posted_jobs.txt"
          # Define the host path where the 'posted_jobs.txt' is cached.
          HOST_POSTED_JOBS_PATH="${{ github.workspace }}/posted_jobs.txt"

          # Execute the Docker container.
          # --rm: Automatically removes the container after it exits.
          # --name: Assigns a name for easy identification in Docker logs/management.
          # -e: Passes environment variables, including sensitive tokens from GitHub Secrets
          #     and the debug flag.
          # -v: Mounts the 'posted_jobs.txt' file from the host (cached from previous runs)
          #     into the container, ensuring persistent state.
          docker run --rm \
            --name devops-job-scraper-run \
            -e TELEGRAM_BOT_TOKEN="${{ secrets.TELEGRAM_BOT_TOKEN }}" \
            -e TELEGRAM_CHAT_ID="${{ secrets.TELEGRAM_CHAT_ID }}" \
            -e POSTED_JOBS_FILE="${CONTAINER_POSTED_JOBS_PATH}" \
            -e DEBUG_ENABLED="${{ env.DEBUG_ENABLED }}" \
            -v "${HOST_POSTED_JOBS_PATH}:${CONTAINER_POSTED_JOBS_PATH}" \
            ${{ secrets.DOCKERHUB_USERNAME }}/devops-job-scraper:latest # Uses the 'latest' image, which was just built/pushed.

      - name: Upload Posted Jobs File as Artifact
        # Uploads the updated 'posted_jobs.txt' file as a workflow artifact.
        # This provides a snapshot of the processed jobs for auditing and debugging,
        # irrespective of whether the job succeeded or failed (due to 'if: always()').
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: posted-jobs-file
          path: posted_jobs.txt # The file to upload from the runner's workspace.
